### ISSUE TITLE
接收关注和取关消息时报错

### ISSUE THREAD

**Issue by sanlian114514** [S-i-l-v-e-t/YHChatPythonSDK#1]
报错内容:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/bottle.py", line 876, in _handle
    return route.call(**args)
  File "/usr/local/lib/python3.10/site-packages/bottle.py", line 1759, in wrapper
    rv = callback(*a, **ka)
  File "/usr/home/sanlian114514/yuhu/YHlib/YHlib.py", line 135, in onRecvPost
    msgbox=geneBaseBox(json,False)
  File "/usr/home/sanlian114514/yuhu/YHlib/YHlib.py", line 82, in geneBaseBox
    msgbox["type"]=json["event"]["chat"]["chatType"]
KeyError: 'chat'

**Comment by sanlian114514** [comment]
解决方案:在YHlib.py的82行,将msgbox["type"]=json["event"]["chat"]["chatType"]改为
msgbox["type"]=jsons["header"]["eventType"]

**Comment by snowy-yang** [comment]
嘿嘿嘿

**Comment by sanlian114514** [comment]
> 解决方案:在YHlib.py的82行,将msgbox["type"]=json["event"]["chat"]["chatType"]改为 msgbox["type"]=jsons["header"]["eventType"]

md
我撤回
这俩type不是一个type

> 嘿嘿嘿

**Comment by sanlian114514** [comment]
> a
b

**Comment by S-i-l-v-e-t** [comment]
我的问题，我有一段时间没上云湖了，明天仔细看看
